/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personalassignment;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.Scanner;
//import java.sql.*;

/**
 *
 * @author velma
 */
public class LoginForm extends javax.swing.JFrame{
Container cont=getContentPane();
   
    public LoginForm() {
        initComponents();
       // Container cont=fr.getContentPane();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        JFrame fr=new JFrame("LOGIN FORM");
     
//PANELS;
        JPanel jp=new JPanel();
        jp.setLayout(new BoxLayout(jp, BoxLayout.PAGE_AXIS));
        jp.setBackground(new java.awt.Color(255,148,120));
        JPanel jp1=new JPanel();
        jp1.setBackground(new java.awt.Color(242,38,19));
        JPanel jp2=new JPanel();
        jp2.setBackground(new java.awt.Color(242,38,19));
        JPanel jp3=new JPanel();
        jp3.setBackground(new java.awt.Color(242,38,19));
//USERNAME RECORDS;
        JLabel jlu=new JLabel("Username:");
        jlu.setFont(new Font("Tahoma", Font.ITALIC, 24));
        JTextField name=new JTextField();
        name.setPreferredSize(new Dimension(200, 40));
        name.setFont(new Font("Times new Roman", Font.ITALIC, 18));
        
//PASSWORD RECORDS;
        JLabel jlp=new JLabel("Password:");
        jlp.setFont(new Font("Tahoma", Font.ITALIC, 24));
        JPasswordField jpass=new JPasswordField();
        jpass.setPreferredSize(new Dimension(200, 40));
        jpass.setFont(new Font("Times new Roman", Font.ITALIC, 18));
        
//LOGIN BUTTON
        JButton login=new JButton("LOGIN");
        login.setFont(new Font("Lucida Calligraphy", Font.ITALIC, 24));
       login.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    {
   String username = name.getText();
   String password = jpass.getText();
   if(name.equals("Velma") && jpass.equals("1234"))
   {
     JOptionPane.showMessageDialog(fr,"WELCOME VELMA!");
      JFrame DashBoard=new JFrame();
      DashBoard.setVisible(true);
      fr.dispose();
    }
    else
    {
      JOptionPane.showMessageDialog(fr,"Incorrect login or password","Error",JOptionPane.ERROR_MESSAGE); 
    }}
                    }});
       
 //DASHBOARD BUTTON      
       JButton dashboard=new JButton("DASHBOARD");
        dashboard.setFont(new Font("Lucida Calligraphy", Font.ITALIC, 24));
        dashboard.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                   DashBoard db=new DashBoard();
                   db.pack();
                   db.setVisible(true);
                   fr.dispose();
        }
        });
                    
//CANCEL BUTTON
        JButton cancel=new JButton("CANCEL");
        cancel.setFont(new Font("Lucida Calligraphy", Font.ITALIC, 24));
        cancel.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    System.exit(0);
        }
        });
        
//ADDITION OF ITEMS TO THE PANELS;
        jp.add(Box.createRigidArea(new Dimension(4,4)));
        jp.add(jp1);
        jp.add(jp2);
        jp.add(jp3);
        jp1.add(jlu);
        jp1.add(name);
        jp2.add(jlp);
        jp2.add(jpass);
        jp3.add(login);
        jp3.add(dashboard);
        jp3.add(cancel);
        
//ADDITION OF ITEMS TO THE FRAME;
        fr.add(jp);
        fr.setMinimumSize(new Dimension(600, 400));
        fr.pack();
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fr.setVisible(true);
        fr.setLocationRelativeTo(null);
        
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
            }
        
              
            
        });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
