/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personalassignment;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   // public void actionPerformed(ActionEvent e) {
    
    public static void main(String args[]) {
        //LoginForm lg=new LoginForm();
     JFrame fr=new JFrame("REGISTRATION FORM");
            fr.setForeground(new java.awt.Color(255,148,120));
        JPanel jp=new JPanel();
            jp.setLayout(new BoxLayout(jp, BoxLayout.PAGE_AXIS));
            jp.setBackground(new java.awt.Color(252,185,65));
        JPanel jp1=new JPanel();
            jp1.setBackground(new java.awt.Color(252,185,65));
        JPanel jp2=new JPanel();
            jp2.setBackground(new java.awt.Color(252,185,65));
        JPanel jp3=new JPanel();
            jp3.setBackground(new java.awt.Color(252,185,65));
            
//FIRST NAME RECORDS;
        JLabel jla=new JLabel("First Name:");
        jla.setFont(new Font("Tahoma", Font.ITALIC, 24));
        JTextField fname=new JTextField();
        fname.setPreferredSize(new Dimension(200, 40));
        fname.setFont(new Font("Times new Roman", Font.ITALIC, 18));
        
//LAST NAME RECORDS;
        JLabel jlb=new JLabel("Last Name:");
        jlb.setFont(new Font("Tahoma", Font.ITALIC, 24));
        JTextField lname=new JTextField();
        lname.setPreferredSize(new Dimension(200, 40));
        lname.setFont(new Font("Times new Roman", Font.ITALIC, 18));
        
//TELEPHONE NUMBER RECORDS;
        JLabel jlc=new JLabel("Telephone No:");
        jlc.setFont(new Font("Tahoma", Font.ITALIC, 24));
        JTextField telno=new JTextField();
        telno.setPreferredSize(new Dimension(200, 40));
        telno.setFont(new Font("Times new Roman", Font.ITALIC, 18));
        
//GENDER SELECTION RECORDS;
        JLabel jlf=new JLabel("Gender:");
        jlf.setFont(new Font("Tahoma", Font.ITALIC, 24));
        JComboBox gender=new JComboBox();
        gender.setFont(new Font("Times new Roman", Font.ITALIC, 18));
        
//DATE OF BIRTH RECORDS;
        JLabel jld=new JLabel("Date Of Birth:");
        jld.setFont(new Font("Tahoma", Font.ITALIC, 24));
        JTextField dob=new JTextField();
        dob.setPreferredSize(new Dimension(200, 40));
        dob.setFont(new Font("Times new Roman", Font.ITALIC, 18));
        
//AGE RECORDS;
        JLabel jle=new JLabel("Age:");
        jle.setFont(new Font("Tahoma", Font.ITALIC, 24));
        JTextField age=new JTextField();
        age.setPreferredSize(new Dimension(200, 40));
        age.setFont(new Font("Times new Roman", Font.ITALIC, 18));
       
//REGISTER BUTTON;
       JButton register=new JButton("REGISTER");
            register.setFont(new Font("Lucida Calligraphy", Font.ITALIC, 24));
            register.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    JButton register=new JButton("REGISTER");
    if(e.getSource()==register){
        int x=0;
     String s1 = fname.getText();
     String s2 = lname.getText();
     String s3 = telno.getText();
     Object s4  =gender.getSelectedItem();
     String s5 = dob.getText();
     String s6 = age.getText();

            try{ 
                   Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/assignment","root","");
                   Class.forName("com.mysql.cj.jdbc");
                   
                PreparedStatement pst = con.prepareStatement("insert into registrationform values('Daniella','Naitore','0722773664','10/01/1994','28')");

                    pst.setString(1, s1);

                    pst.setString(2, s2);

                    pst.setString(3, s3);

                    pst.setString(4, s5);

                    pst.setString(5, s6);

                    pst.setObject(6, s4);

                    ResultSet rs = pst.executeQuery();
                    
                    x++;

                    if (x > 0)
                    {

                        JOptionPane.showMessageDialog(register, "Data Saved Successfully");

                    }

                }
          catch (Exception ex)
                {

                    System.out.println(ex);

                
                }}}});
            
//LOGOUT BUTTON;                   
        JButton logout=new JButton("LOGOUT");
            logout.setFont(new Font("Lucida Calligraphy", Font.ITALIC, 24));
            logout.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    LoginForm lg=new LoginForm();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        fr.dispose();
             }});
            
//RESET RECORDS BUTTON;           
        JButton reset=new JButton("RESET");
            reset.setFont(new Font("Lucida Calligraphy", Font.ITALIC, 24));
            reset.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    fname.setText("");
                    gender.setSelectedItem("Male");
                    lname.setText("");
                    dob.setText("");
                    age.setText("");
                    telno.setText("");
               }});
            
//ADDITION OF ITEMS;
        jp.add(Box.createRigidArea(new Dimension(4,4)));
        jp.add(jp1);
        jp.add(jp2);
        jp.add(jp3);
        
        jp1.add(jla);
        jp1.add(fname);
        jp1.add(jlb);
        jp1.add(lname);
        jp1.add(jlc);
        jp1.add(telno);
        
        jp2.add(jlf);
        jp2.add(gender);
           gender.addItem("MALE");
           gender.addItem("FEMALE");
        jp2.add(jld);
        jp2.add(dob);
        jp2.add(jle);
        jp2.add(age);
                
        jp3.add(register);
        jp3.add(logout);
        jp3.add(reset);
        
        fr.add(jp);
        fr.setMinimumSize(new Dimension(400, 400));
        fr.pack();
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fr.setVisible(true);
        fr.setLocationRelativeTo(null);
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
